import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import GuestCartModal from "@/components/GuestCartModal";
import Navbar from "@/components/navbar";
import { getCategorias } from "@/lib/firebase-cache";
import { ProductsProvider } from "@/providers/ProductsProvider";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }) {
  const categorias = await getCategorias()
  return (
    <html lang="es">
      <body>
        <ProductsProvider>
        <AuthProvider>
          <CartProvider>
            <GuestCartModal />
            <Navbar categorias={categorias} />
            {children}
          </CartProvider>
        </AuthProvider>
        </ProductsProvider>
      </body>
    </html>
  )
}
